CREATE DATABASE EmailsKtdra;
USE EmailsKtdrea;

CREATE TABLE EmailClient(
id_email	BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
email		VARCHAR(50) NOT NULL UNIQUE,
createAt	DATETIME DEFAULT CURRENT_TIMESTAMP 
);